### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by RitvikJoshi** [StackStorm-Exchange/stackstorm-slack#58]
st2 run slack.chat.postMessage token="<token>" text="This is test notification" channel="<channel>"
.
id: 5f1f0194f22c04cacf04fb64
action.ref: slack.chat.postMessage
context.user: user
parameters: 
  channel: <channel>
  text: This is test notification
  token: <token>
status: failed
start_timestamp: Mon, 27 Jul 2020 16:32:20 UTC
end_timestamp: Mon, 27 Jul 2020 16:32:20 UTC
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/slack/actions/run.py", line 30, in run
    for key in params.keys():
RuntimeError: dictionary changed size during iteration
"
  stdout: ''

**Comment by namachieli** [comment]
This should be able to be closed
