### ISSUE TITLE
Code seems to have compatibility issues with 3.7

### ISSUE THREAD

**Issue by RitvikJoshi** [StackStorm-Exchange/stackstorm-slack#59]
The run.py file is using **dict.iteritems()** function call on line  44. The **iteritems** function call is deprecated now and is throwing error

  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/slack/actions/run.py", line 64, in run
    data = urlencode(encode_obj(params))
  File "/opt/stackstorm/packs/slack/actions/run.py", line 60, in encode_obj
    return encode_dict(in_obj)
  File "/opt/stackstorm/packs/slack/actions/run.py", line 44, in encode_dict
    for k, v in in_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by armab** [comment]
@punkrokk can you please elaborate more about closing an issue?

**Comment by punkrokk** [comment]
Sorry - I was gonna respond and my kid got to my computer.

**Comment by punkrokk** [comment]
Hi @RitvikJoshi, it looks like this pack hasn't been upgrade for python 3 compatibility. In python 3 `.items` needs to be used. 

I think if one were to add this to the top of the action, that would solve for the `AttributeError`: 
```
from future.utils import iteritems
```

Would you be able to make a PR for this?

**Comment by namachieli** [comment]
This should be able to be closed
